# Tools
from dataclasses import dataclass
from enum import verify
import itertools
import json
import math
import random

# Database
import sqlite3

# Security
import hashlib
import secrets
import uuid

# Specific Tools
from typing import Any
from itertools import product


from randomuser import RandomUser

# Debug
from icecream import ic


CHUNK_SIZE = 32
CHUNKS_PER_AXIS = 8
SPACEMENT = CHUNK_SIZE

class Chunk:
    def __init__(self, center: tuple[float, float, float], size: int = 32) -> None:
        self.center = center
        self.size = size
        half = size / 2
        
        self.x_range = (center[0] - half, center[0] + half)
        self.y_range = (center[1] - half, center[1] + half)
        self.z_range = (center[2] - half, center[2] + half)



class Tools():
    def __init__(self):
        pass
    
    def generate_chunk_centers(self, n_chunks: int, step: int) -> list:
        """Generates center position for a given number of chunks.

        Args:
            n_chunks (int): number of chunks to generate
            step (int): current step size for each chunk

        Returns:
            list: list representing the center positions of the chunks
        """
        half = (n_chunks // 2)
        
        return [
            step * (i - half) +
            step / 2 
            for i in range(n_chunks)
        ]  

    def calc_distance(self, p1: tuple, p2: tuple) -> float:
        """Calculates the Euclidean distance between two points in 3D space.

        Args:
            p1 (tuple): First point in 3D space, represented as a tuple (x, y, z)
            p2 (tuple): Second point in 3D space, represented as a tuple (x, y, z)

        Returns:
            float: The Euclidean distance between the two points.
        """
        return math.sqrt(
            (p1[0] - p2[0]) ** 2 +
            (p1[1] - p2[1]) ** 2 +
            (p1[2] - p2[2]) ** 2
        )
    
    def verify_distance(self, cube: tuple, other_cubes: list[tuple], min_distance: int = 5) -> bool:
        """Verifies if a given cube is at least a minimum distance away from all other cubes.

        Args:
            cube (tuple): 3D position of the cube represented as a tuple (x, y, z)
            other_cubes (list[tuple]): list of other cubes' positions, each represented as a tuple (x, y, z)
            min_distance (int, optional): Minimum distance that must be maintained from other cubes. Defaults to 5.

        Returns:
            bool: True if the cube is at least the minimum distance away from all other cubes, False otherwise.
        """
        
        for o_cube in other_cubes:
            if self.calc_distance(cube, o_cube) < min_distance:
                return False
        return True

    def gen_random_position(self, other_cubes: list[tuple], min_distance: int = 5, chunk: Chunk | None = None):
        """Generates a random position within a specified chunk that is at least a minimum distance away from other cubes.

        Args:
            other_cubes (list[tuple]):  List of positions of other cubes, each represented as a tuple (x, y, z).
            min_distance (int, optional): _descr. Defaults to 5.
            chunk (Chunk | None, optional): _description_. Defaults to None.
        """
        assert chunk is not None, "You need to pass a Chunk"
        
        while True:
            new_position = (
                random.uniform(*chunk.x_range),
                random.uniform(*chunk.y_range),
                random.uniform(*chunk.z_range)
            )
        
        if verify_distance(new_position, other_cubes, min_distance):
            return new_position

class HashTools():
    def __init__(self) -> None:
        pass
    
    def gen_salt(self, size: int = 16) -> str:
        """Generates a salt string

        Args:
            size (int, optional): _description_. Defaults to 16.

        Returns:
            str: Salt using secrets.token_hex
        """
        
        return secrets.token_hex(size)
    
    def hash_password(self, password: str, salt: str) -> str:
        """Creates a hash_password using password + salt

        Args:
            password (str): string password
            salt (str): salt generated by gen_salt

        Returns:
            str: hash (sha256) as string (using encoded salt_password)
        """
        salt_password = password + salt
        hash_result = hashlib.sha256(salt_password.encode()).hexdigest()
        return hash_result
