# Tools
from dataclasses import dataclass
from enum import verify
import itertools
import json
import math
from os import error
import random

# Database
import sqlite3

# Security
import hashlib
import secrets
import uuid

# Specific Tools
from typing import Any
from itertools import product


from randomuser import RandomUser

# Debug
from icecream import ic


CHUNK_SIZE = 32
CHUNKS_PER_AXIS = 8
SPACEMENT = CHUNK_SIZE

class Chunk:
    def __init__(self, center: tuple[float, float, float], size: int = 32) -> None:
        self.center = center
        self.size = size
        half = size / 2
        
        self.x_range = (center[0] - half, center[0] + half)
        self.y_range = (center[1] - half, center[1] + half)
        self.z_range = (center[2] - half, center[2] + half)


class Vector3:
    def __init__(self, entry_tuple: tuple[float, float, float]):
        self.raw_tuple: tuple[float, float, float] = entry_tuple
        
        self.x = entry_tuple[0]
        self.y = entry_tuple[1]
        self.z = entry_tuple[2]

class Tools():
    def __init__(self):
        pass
    
    def generate_chunk_centers(self, n_chunks: int, step: int) -> list:
        """Generates center position for a given number of chunks.

        Args:
            n_chunks (int): number of chunks to generate
            step (int): current step size for each chunk

        Returns:
            list: list representing the center positions of the chunks
        """
        half = (n_chunks // 2)
        
        return [
            step * (i - half) +
            step / 2 
            for i in range(n_chunks)
        ]  

    def calc_distance(self, p1: tuple, p2: tuple) -> float:
        """Calculates the Euclidean distance between two points in 3D space.

        Args:
            p1 (tuple): First point in 3D space, represented as a tuple (x, y, z)
            p2 (tuple): Second point in 3D space, represented as a tuple (x, y, z)

        Returns:
            float: The Euclidean distance between the two points.
        """
        return math.sqrt(
            (p1[0] - p2[0]) ** 2 +
            (p1[1] - p2[1]) ** 2 +
            (p1[2] - p2[2]) ** 2
        )
    
    def verify_distance(self, cube: tuple, other_cubes: list[tuple], min_distance: int = 5) -> bool:
        """Verifies if a given cube is at least a minimum distance away from all other cubes.

        Args:
            cube (tuple): 3D position of the cube represented as a tuple (x, y, z)
            other_cubes (list[tuple]): list of other cubes' positions, each represented as a tuple (x, y, z)
            min_distance (int, optional): Minimum distance that must be maintained from other cubes. Defaults to 5.

        Returns:
            bool: True if the cube is at least the minimum distance away from all other cubes, False otherwise.
        """
        
        for o_cube in other_cubes:
            if self.calc_distance(cube, o_cube) < min_distance:
                return False
        return True

    def gen_random_position(self, other_cubes: list[tuple], min_distance: int = 5, chunk: Chunk | None = None):
        """Generates a random position within a specified chunk that is at least a minimum distance away from other cubes.

        Args:
            other_cubes (list[tuple]):  List of positions of other cubes, each represented as a tuple (x, y, z).
            min_distance (int, optional): _descr. Defaults to 5.
            chunk (Chunk | None, optional): _description_. Defaults to None.
        """
        assert chunk is not None, "You need to pass a Chunk"
        
        while True:
            new_position = (
                random.uniform(*chunk.x_range),
                random.uniform(*chunk.y_range),
                random.uniform(*chunk.z_range)
            )
        
        if verify_distance(new_position, other_cubes, min_distance):
            return new_position

class HashTools():
    def __init__(self) -> None:
        pass
    
    def gen_salt(self, size: int = 16) -> str:
        """Generates a salt string

        Args:
            size (int, optional): _description_. Defaults to 16.

        Returns:
            str: Salt using secrets.token_hex
        """
        
        return secrets.token_hex(size)
    
    def hash_password(self, password: str, salt: str) -> str:
        """Creates a hash_password using password + salt

        Args:
            password (str): string password
            salt (str): salt generated by gen_salt

        Returns:
            str: hash (sha256) as string (using encoded salt_password)
        """
        salt_password = password + salt
        hash_result = hashlib.sha256(salt_password.encode()).hexdigest()
        return hash_result


class DatabaseTools:
    def __init__(self, dbpath: str, chunks: list[Chunk], tools: Tools, hash_tools: HashTools) -> None:
        self.conn: sqlite3.Connection = sqlite3.connect(dbpath)
        self.conn.row_factory = sqlite3.Row
        self.cursor = self.conn.cursor()
        self.chunks = chunks
        self.tools = tools
        self.hash_tools = hash_tools
    
    def storeSaltHash(self, user_id: str, salt: str) -> None:
        """ Stores the salt for a user in the database.

        Args:
            user_id (str): Current user id
            salt (str): Current user salt to be stored
        """
        cmd: str = (
            "INSERT INTO salt(user_id, salt) " 
            "VALUES "
            "(?, ?)"
        )
        
        try:
            self.cursor.execute(cmd, (user_id, salt))
            
        except sqlite3.IntegrityError as e:
            print(f"Sqlite3 integrity error: {e=}")

        except sqlite3.Error as e:
            print(f"Sqlite3 error: {e=}")

    def newUser(self, username: str, email: str, raw_password: str) -> dict | None:
        """ Creates a new user in the database.

        Args:
            username (str): user name
            email (str): user email
            raw_password (str): user string password

        Returns:
            dict | None: Returns the created user as a dictionary or None if an error occurs.
        """
        cmd: str = (
            "INSERT INTO user"
            "(id, username, email, passowrd_hash)"
            "VALUES (?, ?, ?, ?)"
        )
        
        user_id: str = uuid.uuid4().__str__()
        salt: str = self.hash_tools.gen_salt()
        password_hash = self.hash_tools.hash_password(
            password=raw_password,
            salt=salt
        )
        
        data = (user_id, username, email, password_hash)
        try:
            self.cursor.execute(cmd, data)
            self.storeSaltHash(user_id=user_id, salt=salt)
            
            user_created: dict = self.getUserById(user_id)
            
            if "error" in user_created.keys():
                return user_created
            else:
                self.newCube(user_created["id"])
                return user_created
            
        except sqlite3.IntegrityError as e:
            print(f"Sqlite integrity error: {e=}")
        except sqlite3.Error as e:
            print(f"Sqlite error: {e=}")
        except Exception as e:
            print(f"Unhandled error: {e=}")

    def newCube(self, user_id: str) -> None:
        """ Creates a new cube for a user in the database.

        Args:
            user_id (str): User id to create the cube for
        """
        cmd: str = (
            "INSERT INTO cube"
            "(id, owner_id, position_x, position_y, position_z, size) "
            "VALUES"
            "(?, ?, ?, ?, ?, ?)"
        )
        
        cube_id: str = uuid.uuid4().__str__()
        random_chunk: Chunk = random.choice(self.chunks)
        chunk_cubes: list[tuple[float, float, float]] = self.getChunkCubesXYZ(random_chunk)
        new_position: tuple[float, float, float] = self.tools.gen_random_position(
            other_cubes=chunk_cubes,
            min_distance=5,
            chunk=random_chunk
        )
        npv3: Vector3 = Vector3(new_position)
        data: tuple = (
            cube_id, user_id, 
            npv3.x, npv3.y, npv3.z
        )
        
        try:
            self.cursor.execute(cmd, data)
        except sqlite3.IntegrityError as e:
            print(f"Sqlite integrity error: {e=}")
        except sqlite3.Error as e:
            print(f"Sqlite error: {e=}")
    
    def getSaltHashes(self) -> list[dict]:
        """ Retrieves all salt hashes from the database."""
        self.cursor.execute("SELECT * FROM salt")
        return self.result_as_ldisct(self.cursor.fetchall())
    
    def getChunkCubesXYZ(self, chunk: Chunk) -> list[tuple[float, float, float]]:
        """ Retrieves all cubes' positions within a specified chunk.

        Args:
            chunk (Chunk): The chunk to retrieve cubes from, containing its center and size.

        Returns:
            list[tuple[float, float, float]]: A list of tuples representing the positions of cubes within the specified chunk.
        """
        cmd: str = (
            "SELECT position_x, position_y, position_z FROM CUBE WHERE "
            "position_x BETWEEN ? AND ? AND"
            "position_y BETWEEN ? AND ? AND"
            "position_z BETWEEN ? AND ? "
        )
        
        self.cursor.execute(cmd, (
            *chunk.x_range,
            *chunk.y_range,
            *chunk.z_range,
        ))
        
        return self.cursor.fetchall()

    def getUserById(self, user_id: str) -> dict:
        """ Retrieves a user by their ID from the database.

        Args:
            user_id (str): The ID of the user to retrieve.

        Returns:
            dict: A dictionary representing the user if found, or an error message if not found.
        """
        cmd: str = "SELECT * FROM USER WHERE id = ?"
        results: list = self.cursor.execute(cmd, (user_id, )).fetchall()
        
        errormsg = {"error": "User not found"}
        user: dict = self.result_as_ldisct(results)[0] if len(results) > 0 else errormsg
        
        return user
    
    def getUsers(self) -> list[dict]:
        """ Retrieves all users from the database.

        Returns:
            list[dict]: A list of dictionaries representing all users in the database.
        """
        self.cursor.execute("SELECT * FROM user")
        return self.result_as_ldisct(self.cursor.fetchall())
    
    def result_as_ldisct(self, content: list[Any]) -> list[dict]:
        """ Converts a list of sqlite3.Row objects to a list of dictionaries."""
        if not content:
            return []

        return [dict(row) for row in content]
